- name: Windows task
  hosts: all
  gather_facts: false
  tasks:
    - name: No8 Delete File
      win_file:
        path: "{{ item }}"
        state: absent
      with_items:
        - C:\Users\Administrator\Desktop\file1.txt
        - C:\Users\Administrator\Desktop\file2.txt
        
