- name: No10 ComputerHostName Change
  hosts: all
  gather_facts: false
  tasks:
    - win_hostname:
        name: "{{ newhost1 }}"
      register: res
  
    - win_reboot:
        reboot_timeout: 120
      when: res.reboot_required == true
    
    - local_action: wait_for host={{ hosts }} port={{ port }} delay=30
      when: res.reboot_required == true
