- name: Windows task
  hosts: all
  gather_facts: false
  tasks:
    - name: Windows Update
      win_updates:
        ##category_names: ['SecurityUpdates']
      register: result
      log_path: C:\Users\Administrator\Desktop\wu.txt
  
    - debug: var=result
